name: terminal-parrot 
adopt-info: terminal-parrot
summary: Parrot for your terminal 
description: |
  You didn't know there was a party in your terminal, but there is! 
  To run, type "terminal-parrot"
  To quit, hit the `ESC` key
  Enjoy! 

license: MIT

base: core18
grade: stable
confinement: strict

apps:
  terminal-parrot:
    command: terminal-parrot

parts: 
  terminal-parrot:
    source: .
    source-type: git
    plugin: go
    go-importpath: github.com/jmhobbs/terminal-parrot
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
