name: terminal-parrot 
adopt-info: terminal-parrot
summary: Parrot for your terminal 
description: |
  You didn't know there was a party in your terminal, but there is! 
  To run, type "terminal-parrot"
  To quit, hit the `ESC` key
  Enjoy! 

contact: https://github.com/kz6fittycent/terminal-parrot/issues
issues: https://github.com/kz6fittycent/terminal-parrot/issues
source-code: https://github.com/jmhobbs/terminal-parrot
donation: https://www.patreon.com/kz6fittycent

license: MIT
base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  s390x:
    build-on: [s390x]
    build-for: [s390x]
  ppc64el:
    build-on: [ppc64el]
    build-for: [ppc64el]

apps:
  terminal-parrot:
    command: bin/terminal-parrot

parts: 
  terminal-parrot:
    source: https://github.com/jmhobbs/terminal-parrot
    source-type: git
    plugin: go
    build-snaps:
      - go
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
